language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra
    - extra-android-m2repository

    # Update Android SDK Tools
    - tools

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle