language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-23.0.3
    - android-23

    # Update Android SDK Tools
    - tools

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
- $HOME/.m2