language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

    # Update Android SDK Tools
    - tools

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle